name: pizza-ai
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _python_abi3_support=1.0
  - appnope=0.1.4
  - asttokens=3.0.1
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - certifi=2025.11.12
  - comm=0.2.3
  - cpython=3.12.12
  - debugpy=1.8.16
  - decorator=5.2.1
  - executing=2.2.1
  - expat=2.7.3
  - h11=0.16.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - idna=3.11
  - ipykernel=7.1.0
  - ipython=9.8.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jupyter_client=8.7.0
  - jupyter_core=5.9.1
  - krb5=1.21.3
  - libcxx=20.1.8
  - libedit=3.1.20250104
  - libexpat=2.7.3
  - libffi=3.4.4
  - libsodium=1.0.20
  - libzlib=1.3.1
  - matplotlib-inline=0.2.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - openssl=3.6.0
  - packaging=25.0
  - parso=0.8.5
  - pexpect=4.9.0
  - pip=25.3
  - platformdirs=4.5.1
  - prompt-toolkit=3.0.52
  - psutil=7.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.12.12
  - python-dateutil=2.9.0.post0
  - python-gil=3.12.12
  - python_abi=3.12
  - pyzmq=27.1.0
  - readline=8.3
  - setuptools=80.9.0
  - six=1.17.0
  - sniffio=1.3.1
  - sqlite=3.51.0
  - stack_data=0.6.3
  - tk=8.6.15
  - tornado=6.5.4
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - tzdata=2025b
  - wcwidth=0.2.14
  - wheel=0.45.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zlib=1.3.1
  - pip:
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.0
      - attrs==25.4.0
      - authlib==1.6.6
      - beartype==0.22.9
      - cachetools==6.2.4
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cloudpickle==3.1.2
      - cryptography==46.0.3
      - cyclopts==4.4.2
      - diskcache==5.6.3
      - dnspython==2.8.0
      - docstring-parser==0.17.0
      - docutils==0.22.4
      - email-validator==2.3.0
      - exceptiongroup==1.3.1
      - fakeredis==2.33.0
      - fastapi==0.128.0
      - fastapi-cli==0.0.20
      - fastapi-cloud-cli==0.8.0
      - fastar==0.8.0
      - fastmcp==2.14.1
      - httptools==0.7.1
      - httpx-sse==0.4.3
      - importlib-metadata==8.7.1
      - jaraco-classes==3.4.0
      - jaraco-context==6.0.2
      - jaraco-functools==4.4.0
      - jinja2==3.1.6
      - jsonschema==4.25.1
      - jsonschema-path==0.3.4
      - jsonschema-specifications==2025.9.1
      - keyring==25.7.0
      - lupa==2.6
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - mcp==1.25.0
      - mdurl==0.1.2
      - more-itertools==10.8.0
      - openapi-pydantic==0.5.1
      - opentelemetry-api==1.39.1
      - opentelemetry-exporter-prometheus==0.60b1
      - opentelemetry-instrumentation==0.60b1
      - opentelemetry-sdk==1.39.1
      - opentelemetry-semantic-conventions==0.60b1
      - pathable==0.4.4
      - pathvalidate==3.3.1
      - prometheus-client==0.23.1
      - py-key-value-aio==0.3.0
      - py-key-value-shared==0.3.0
      - pycparser==2.23
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydantic-extra-types==2.10.6
      - pydantic-settings==2.12.0
      - pydocket==0.16.3
      - pyjwt==2.10.1
      - pyperclip==1.11.0
      - python-dotenv==1.2.1
      - python-json-logger==4.0.0
      - python-multipart==0.0.21
      - pyyaml==6.0.3
      - redis==7.1.0
      - referencing==0.36.2
      - requests==2.32.5
      - rich==14.2.0
      - rich-rst==1.3.2
      - rich-toolkit==0.17.1
      - rignore==0.7.6
      - rpds-py==0.30.0
      - sentry-sdk==2.48.0
      - shellingham==1.5.4
      - sortedcontainers==2.4.0
      - sse-starlette==3.1.1
      - starlette==0.50.0
      - typer==0.21.0
      - typing-inspection==0.4.2
      - urllib3==2.6.2
      - uvicorn==0.40.0
      - uvloop==0.22.1
      - watchfiles==1.1.1
      - websockets==15.0.1
      - wrapt==1.17.3
      - zipp==3.23.0
prefix: /opt/homebrew/anaconda3/envs/pizza-ai
